CREATE DATABASE apitest;
USE restapi;
CREATE TABLE salarie (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  salno VARCHAR(255) NOT NULL,
  salname VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,
);
